FROM python:3.11.10-slim

# Set the working directory
WORKDIR /app

# Copy all project files into the container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r fastapi uvicorn plyvel requests

# Expose the port your FastAPI app runs on
EXPOSE 8080

# Run the FastAPI application
CMD ["python3", "node.py", "--port", "8080", "--host", "0.0.0.0", "--region", "Hyderabad"]
